name: flutter_app_test
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  firebase_core: ^0.7.0
  firebase_analytics: ^7.0.1
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0
  firebase_database: ^6.0.0
  google_sign_in: ^4.5.9
  provider: ^4.3.3
  font_awesome_flutter: ^8.11.0
  flutter_login_facebook: ^0.5.0
  google_fonts: ^1.1.2
  badges: ^1.1.6
  carousel_slider: ^3.0.0
  url_launcher: ^5.7.6
  flutter_form_bloc: ^0.11.0
  searchable_dropdown: ^1.1.3
  datetime_picker_formfield: ^1.0.0
  image_picker: ^0.6.7+22
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/event_images/
    - assets/guest_images/
    - assets/images/flutter-logo-round.png
    - assets/data/records.json

  fonts:
    - family: DanaYadAlefAlefAlef
      fonts:
        - asset: fonts/DanaYadAlefAlefAlef-Normal.otf
    - family: yehudaclm Bold
      fonts:
        - asset: fonts/yehudaclm-bold-webfont.ttf
    - family: yehudaclm Light
      fonts:
        - asset: fonts/yehudaclm-light-webfont.ttf
    - family: comixno2clm Bold
      fonts:
        - asset: fonts/comixno2clm_bold-webfont.ttf
    - family: comixno2clm Medium
      fonts:
        - asset: fonts/comixno2clm_medium-webfont.ttf
    - family: Abraham
      fonts:
        - asset: fonts/Abraham-Regular.ttf
    - family: elliniaclm bold
      fonts:
        - asset: fonts/elliniaclm-bold-webfont.ttf
    - family: elliniaclm bolditalic
      fonts:
        - asset: fonts/elliniaclm-bolditalic-webfont.ttf
    - family: elliniaclm light
      fonts:
        - asset: fonts/elliniaclm-light-webfont.ttf
    - family: elliniaclm lightitalic
      fonts:
        - asset: fonts/elliniaclm-lightitalic-webfont.ttf
    - family: miriwin
      fonts:
        - asset: fonts/miriwin-webfont.ttf
    - family: nehama
      fonts:
        - asset: fonts/nehama-webfont.ttf


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
