version: '3.9'
services:
  db:
    image: postgres:16-alpine
    container_name: family_events_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: family
      POSTGRES_PASSWORD: family
      POSTGRES_DB: family
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:

